# Application configuration for Inventory Service
spring.application.name=inventory-service
server.port=8083

# Base URL for Product Service
services.product.base-url=http://localhost:8081

# Data base information
db.name=ms_inventory
# 3309 for docker and 3306 for local
db.port=3309

# Database credentials
# For docker, use the following credentials: davidBernal and admin1234
# For local development, you can use your own credentials or the same ones if you have set up your local MySQL with these credentials.
spring.datasource.username=davidBernal
spring.datasource.password=admin1234

# Actuator - health checks
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Swagger configuration
springdoc.swagger-ui.path=/index.html

# Disable Open Session in View to prevent lazy loading issues
spring.jpa.open-in-view=false

#JPA and Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://localhost:${db.port}/${db.name}

