apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: inventory-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-inventory:3306/ms_inventory
        - name: SPRING_DATASOURCE_USERNAME
          value: davidBernal
        - name: SPRING_DATASOURCE_PASSWORD
          value: admin1234
        - name: SERVICES_PRODUCT_BASE_URL
          value: http://product-service:8081
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: ecommerce
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8083
    targetPort: 8083
  type: ClusterIP
