apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-product-pvc
  namespace: ecommerce
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-product
  namespace: ecommerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-product
  template:
    metadata:
      labels:
        app: mysql-product
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_DATABASE
          value: ms_products
        - name: MYSQL_USER
          value: davidBernal
        - name: MYSQL_PASSWORD
          value: admin1234
        - name: MYSQL_ROOT_PASSWORD
          value: admin1234
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mysql-product-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-product
  namespace: ecommerce
spec:
  selector:
    app: mysql-product
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP
